### ISSUE TITLE
Workshop "Limited" Crafting Not Working?

### ISSUE THREAD

**Issue by theqmann** [kitten-science/kitten-scientists#499] opened 2024-03-04 08:32 UTC
### Version Check

- [X] I have updated to `v2.0.0-beta.8` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox

### How are you loading Kitten Scientists?

Bookmarklet

### Describe the Bug

Per the documentation, the Limited button works as follows:

> For a limited item to be crafted, we first look at all the materials that are required for the item to be crafted, and at our current stock for the item. We then calculate how much of our materials would be required to build all the items we already have in stock. If we have more materials than that, then we allow the additional materials to be crafted into more of the craftable item.

> Let's assume you want to craft Beams. A beam costs 175 Wood, and you have 1 beam in stock. KS would then craft the next beam when you have 350 wood available.

In my game, I have 1 million beams in stock, and have 5 million wood max capacity.  Based on the description, it shouldn't craft any more beams until I have 175 million wood (enough to meet the current stock).  When setting Workshop threshold to any value (tried at 0.0, 0.1, and 0.995) it will craft beams immediately when the workshop threshold is met (at 0 threshold, it crafts immediately when wood > 175), without respecting the Limited flag.

**Comment by oliversalzburg** [comment] 2024-03-24 20:20
Can you maybe provide a savegame, just so there are no misunderstandings about the situation? I can't really wrap my head around it without walking through it in the debugger, I fear :(

**Comment by dpatti** [comment] 2024-04-17 03:36
I ran into the same thing and I get the sense that this is explicitly how it was meant to work based on my reading of [this comment](https://github.com/kitten-science/kitten-scientists/blob/main/packages/kitten-scientists/source/WorkshopManager.ts#L189-L192) and the surrounding code. The comment below it applies to crafted materials as well, but only under the condition that they're at their own "max". I think a similar condition for capped resources would make sense where you can exceed the limit only once the required resource is capped. This would make setting a lower workshop trigger a much more viable option, without which you can get into some resource starvation issues.

**Comment by oliversalzburg** [comment] 2024-04-25 15:36
@dpatti Thanks for looking into it. There haven't been any recent changes to how the script works at its core. At this point, it's always highly likely that the script is working as intended. If the intention is the right one, is always up for debate :) So, your analysis is likely to be correct.

Resource crafting just has a lot of edge cases that are hard to all get right, while still keeping the rules simple enough so you always know why things are happening (hopefully). At the very least, I'm always open to further clarify how things should behave.

**Comment by oliversalzburg** [comment] 2024-10-09 16:38
Possibly related to #451

**Comment by oliversalzburg** [comment] 2024-11-10 16:22
I looked into this again from a few different game scenarios. @dpatti is correct, in that everything is actually working exactly as it was designed. That's not saying that the behavior doesn't need changing!

First of all, it's important to know that the term "limited" is highly misleading here. The term is used for this feature historically and has never been revised.

Your expectation, that KS would stop crafting beams until your stock capacity is expanded to craft a larger number of beams, seems perfectly reasonable. After all, the craft is _limited_.

However, _limited_ applies to the resource spending approach **only**. It has no effect on when KS would stop crafting more items. If you want to stop crafting after reaching a given amount in stock, you have to use the "Max" setting.

This is probably not helping at all, and you would much prefer if crafting just worked like expected. I fully agree that crafting is often not working right, and others have also long pointed out that crafting needs to be more configurable.

So that's what we'll do...

**Comment by oliversalzburg** [comment] 2024-11-11 11:40
@dpatti When I was going through the documentation and code yesterday, I felt similarly. I thought about switching the behavior to unlimited when the resource is capped. I ended up not liking it, because it would instantly craft all my resources _unlimited_ after a reset, as all my resources are above cap after a reset.

I theorized about this before in other places; I believe the "Limited" option for crafting needs to be rethought.

- When I check the "Limited" option, what I want to say is "Craft this resource, but try to retain source materials for other stuff".
- When I uncheck the "Limited" option, what I want to say is "Craft this resource as fast as possible".

To me, this sounds like I really want to decide between _conservative_ and _aggressive_ spending. This conservative spending effect needs to be reasonable in scenarios where:

- I have slow income. So I don't want to end up having all my base materials crafted into resources I might only need later.
- I have tons of the base material, but very little of the crafted resource. So I still want to _gradually_ craft the materials into the target resource. This is important for resets with Chronospheres.
- I have no "Max" configured for a craft. I assume that new users prefer to keep the crafts set to infinity to just build up a large stock for game features they might not even have unlocked yet. This is especially tricky. How to you conservatively spend to infinity?

I'm currently thinking about an idea to merge the crafting UI with the Resource Control to achieve the following:

1. Control the lower bound of resources that KS will not touch. The "Stock" value.
2. Control the upper bound of resources the KS will produce. The "Max" value.
3. Control the strategy for how to go from lower to upper bound. The "Limited" value.
4. Control the ratio between resources fed into the strategy, and the resources left in stock. The "Consume" value.

This might also open up entirely new ways of thinking about _triggers_ for crafts, as the "Stock" value for all resources seems to be a trigger value already.

I also noticed that I myself heavily under-utilize these controls as-is, because the UI makes it difficult.

I'm also pretty sure someone else had already suggested to me doing _exactly this_ in the past. I don't even want to claim it as a new idea, but I couldn't find the ticket :smile:

**Comment by oliversalzburg** [comment] 2024-11-13 20:04
Given that everything is actually working as intended, I will close this issue through #785 

I know there is still work to do to meet user expectations in crafting, and the recent research has helped a lot in bringing up new ideas. I'm pretty confident that we will get a valuable solution during the next beta cycle.

**Closed** 2024-11-15 18:11 UTC
Labels: status:confirmed, status:wontfix
